version: '3.3'

services:
  mysql:
    container_name: mysql-server
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'lucas'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root-pw'
    ports:
      - '3306:3306'
    expose:
      - 3306
